### ISSUE TITLE
Instrumentation

### ISSUE THREAD

**Issue by mapesa** [ilabafrica/BLIS#107]
1. How will the different lab equipment (e.g. FACS Counters, Genexpert, ...) interact with kBLIS?
2. Possible steps:
   - Fetch the data
     - Poll the machine for data
     - Listen on a port/socket for data 
     - Read results from a dump file
   - Process the data, bearing in mind the Test from which it was requested
   - Store the data
3. Possible approach:
   - An interface that determines the general flow
   - Implementations define the _nitty gritties_ for particular machines.

**Comment by voleche09** [comment]
Does kblis have any api to integrate to other systems?

**Comment by ereng** [comment]
> Does kblis have any api to integrate to other systems?

https://github.com/ilabafrica/Blis-V3/releases/tag/v3.0-alpha does [to EMR](https://github.com/ilabafrica/emrinterface), [to Automated Machine Client](https://github.com/ilabafrica/EquipmentInterface).... [this](https://github.com/ilabafrica/BLISInterfaceClient) is the Automated Machine Client

**Comment by voleche09** [comment]
Thanks for the quick response.Is there any documentation to start me up quickly on how to use these?
